// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgXIvcEwZwHV-4fG6L84XxZKbZH_anYvQ',
    appId: '1:854289820257:web:dab0706f19e1ec46f51820',
    messagingSenderId: '854289820257',
    projectId: 'welfare-factory',
    authDomain: 'welfare-factory.firebaseapp.com',
    storageBucket: 'welfare-factory.appspot.com',
    measurementId: 'G-PSGNG51PM2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClP77QbOM-m47n8MKuAnOae98c2HAfV6M',
    appId: '1:854289820257:ios:8d1b56a656185c8af51820',
    messagingSenderId: '854289820257',
    projectId: 'welfare-factory',
    storageBucket: 'welfare-factory.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgXIvcEwZwHV-4fG6L84XxZKbZH_anYvQ',
    appId: '1:854289820257:web:2d29da4a69f1959ff51820',
    messagingSenderId: '854289820257',
    projectId: 'welfare-factory',
    authDomain: 'welfare-factory.firebaseapp.com',
    storageBucket: 'welfare-factory.appspot.com',
    measurementId: 'G-NGH6GMVF7K',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClP77QbOM-m47n8MKuAnOae98c2HAfV6M',
    appId: '1:854289820257:ios:8d1b56a656185c8af51820',
    messagingSenderId: '854289820257',
    projectId: 'welfare-factory',
    storageBucket: 'welfare-factory.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYXG8I92XBJfc9MwuqbdbvIOH-qhrf-Q4',
    appId: '1:854289820257:android:29e0614f6c7cc829f51820',
    messagingSenderId: '854289820257',
    projectId: 'welfare-factory',
    storageBucket: 'welfare-factory.appspot.com',
  );

}